/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "HarmonicGainComponent.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class HarmonicSynthesizerVSTProcessorEditor  : public AudioProcessorEditor,
                                            public SliderListener,
                                            public Timer
{
public:
    HarmonicSynthesizerVSTProcessorEditor (HarmonicSynthesizerVSTAudioProcessor&);
    ~HarmonicSynthesizerVSTProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider*) override;

	std::vector<float>* getGainsVector();

private:
    MidiKeyboardComponent midiKeyboard;
    Label infoLabel, gainLabel, delayLabel;
    Slider gainSlider, delaySlider;
    ScopedPointer<ResizableCornerComponent> resizer;
	ScopedPointer<HarmonicGainComponent> harmonicsGain;
    ComponentBoundsConstrainer resizeLimits;

    AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;

    HarmonicSynthesizerVSTAudioProcessor& getProcessor() const
    {
        return static_cast<HarmonicSynthesizerVSTAudioProcessor&> (processor);
    }

    void displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos);
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
